[package]
name = "iban-validator"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "An iban validator written containing rust generated WebAssembly"
repository = "https://github.com/jbosi/iban-validator"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

